name: Tests on code push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.20
        uses: actions/setup-go@v5
        with:
          go-version: "1.20.x"
      - name: Test module - Bruce
        run: go test ./bruce
      - name: Test module - Log
        run: go test ./log
