name: Publish as library

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "running on github ref $GITHUB_REF"

      - name: Exit if not on main branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1

      - name: Publish
        run: GOPROXY=proxy.golang.org go list -m github.com/tukaianirban/sdk.go.common@${{github.ref_name}}
